"""added author id to like model.

Revision ID: 080521e8eb06
Revises: 7e09c3e24336
Create Date: 2021-02-06 10:10:52.734174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080521e8eb06'
down_revision = '7e09c3e24336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_location', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('dataset_location_dataset_id_fkey', 'dataset_location', type_='foreignkey')
    op.add_column('like', sa.Column('author_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('like', 'author_id')
    op.create_foreign_key('dataset_location_dataset_id_fkey', 'dataset_location', 'dataset', ['dataset_id'], ['id'])
    op.drop_column('dataset_location', 'name')
    # ### end Alembic commands ###
