"""added username index

Revision ID: 9381734b2f7d
Revises: c46a9423ebf5
Create Date: 2021-02-07 20:07:49.054531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9381734b2f7d'
down_revision = 'c46a9423ebf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_constraint('user_username_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_index(op.f('ix_user_username'), table_name='user')
    # ### end Alembic commands ###
